server:
  port: 8683
  servlet:
    context-path: /files

spring:
  datasource:
    username:  root
    password: 123456
    url: jdbc:mysql://localhost:3306/hancloud_pf_web?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#&serverTimezone=UTC
#扫描映射文件


logging:
  level:
   com.jscloud: debug